// js/data.js — StyleMart Product Catalogue

const PRODUCTS = [
  {
    id: 1,
    name: "Linen Oversized Blazer",
    brand: "Atelier Co.",
    price: 3499,
    originalPrice: 4999,
    category: "women",
    badge: "Best Seller",
    color: "#C9B8A8",
    emoji: "🧥",
    rating: 4.8,
    reviews: 124,
    description: "Relaxed silhouette in breathable European linen."
  },
  {
    id: 2,
    name: "Slim Chino Trousers",
    brand: "Forma Studio",
    price: 1799,
    originalPrice: 2499,
    category: "men",
    badge: "New",
    color: "#8B9D77",
    emoji: "👖",
    rating: 4.6,
    reviews: 88,
    description: "Tapered fit, stretch fabric — boardroom to bar."
  },
  {
    id: 3,
    name: "Gold Cuff Bracelet",
    brand: "Aurum",
    price: 999,
    originalPrice: 1499,
    category: "accessories",
    badge: "Limited",
    color: "#D4AF37",
    emoji: "⭕",
    rating: 4.9,
    reviews: 57,
    description: "18k gold-plated brass, adjustable sizing."
  },
  {
    id: 4,
    name: "Chelsea Leather Boots",
    brand: "Cobblestone",
    price: 5999,
    originalPrice: 7999,
    category: "footwear",
    badge: "Sale",
    color: "#6B4226",
    emoji: "👢",
    rating: 4.7,
    reviews: 203,
    description: "Full-grain leather, elastic side panels, Cuban heel."
  },
  {
    id: 5,
    name: "Wrap Midi Dress",
    brand: "Atelier Co.",
    price: 2299,
    originalPrice: 2999,
    category: "women",
    badge: null,
    color: "#C4688A",
    emoji: "👗",
    rating: 4.5,
    reviews: 91,
    description: "Fluid crepe fabric, adjustable waist wrap."
  },
  {
    id: 6,
    name: "Merino Crew Sweater",
    brand: "Nordic Knit",
    price: 2799,
    originalPrice: 3499,
    category: "men",
    badge: "New",
    color: "#6B8CAE",
    emoji: "🧶",
    rating: 4.8,
    reviews: 67,
    description: "100% merino wool, ethically sourced."
  },
  {
    id: 7,
    name: "Mini Canvas Tote",
    brand: "Carry On",
    price: 1299,
    originalPrice: 1799,
    category: "accessories",
    badge: null,
    color: "#E8D5B7",
    emoji: "👜",
    rating: 4.4,
    reviews: 145,
    description: "Waxed canvas body, vachetta leather handles."
  },
  {
    id: 8,
    name: "White Leather Sneakers",
    brand: "Cobblestone",
    price: 3299,
    originalPrice: 3999,
    category: "footwear",
    badge: "Best Seller",
    color: "#F0EDE8",
    emoji: "👟",
    rating: 4.9,
    reviews: 312,
    description: "Supple nappa leather, memory foam insole."
  },
  {
    id: 9,
    name: "Silk Slip Skirt",
    brand: "Atelier Co.",
    price: 1899,
    originalPrice: 2599,
    category: "women",
    badge: "Sale",
    color: "#B5A9D4",
    emoji: "👘",
    rating: 4.6,
    reviews: 73,
    description: "Bias-cut silk charmeuse, side slit detail."
  },
  {
    id: 10,
    name: "Tortoise Sunglasses",
    brand: "Aurum",
    price: 1499,
    originalPrice: 1999,
    category: "accessories",
    badge: null,
    color: "#8B6914",
    emoji: "🕶️",
    rating: 4.7,
    reviews: 89,
    description: "UV400 polarised lenses, acetate frames."
  },
  {
    id: 11,
    name: "Oxford Button-Down",
    brand: "Forma Studio",
    price: 1599,
    originalPrice: 1999,
    category: "men",
    badge: null,
    color: "#A8C4D4",
    emoji: "👔",
    rating: 4.5,
    reviews: 156,
    description: "Pinpoint Oxford cotton, button-down collar."
  },
  {
    id: 12,
    name: "Block Heel Mules",
    brand: "Cobblestone",
    price: 2999,
    originalPrice: 3799,
    category: "footwear",
    badge: "New",
    color: "#D4A0A0",
    emoji: "👠",
    rating: 4.6,
    reviews: 44,
    description: "Suede upper, 6cm block heel, open toe."
  }
];
